spring.application.name=decathlon
server.port=5050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/sportlased
spring.datasource.username=postgres
spring.datasource.password=765gso01ja
