spring.application.name=veebipood
server.port=5050
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d73711fgi27c73cv68hg-a.oregon-postgres.render.com/veebipood_database_gye8
spring.datasource.username=veebipood_user
spring.datasource.password=Ok96o6D8cyqoQh2HK4a5vQBTgvA5hoL4